/**
 * @version: 1.0 Alpha-1
 * @author: Coolite Inc. http://www.coolite.com/
 * @date: 18-Dec-2007
 * @copyright: Copyright (c) 2006-2007, Coolite Inc. (http://www.coolite.com/). All rights reserved.
 * @license: Licensed under The MIT License. See license.txt and http://www.datejs.com/license/. 
 * @website: http://www.datejs.com/
 */
(function(){var $D=Date,$P=$D.prototype,$C=$D.CultureInfo;$P.clearTime=function(){this.setHours(0);this.setMinutes(0);this.setSeconds(0);this.setMilliseconds(0);return this;};$P.setTimeToNow=function(){var n=new Date();this.setHours(n.getHours());this.setMinutes(n.getMinutes());this.setSeconds(n.getSeconds());this.setMilliseconds(n.getMilliseconds());return this;};$D.today=$D.tod=function(){return new Date().clearTime();};$D.getDayName=function(dayOfWeek,abbreviated){return(abbreviated&&typeof abbreviated=="boolean")?$C.abbreviatedDayNames[dayOfWeek]:$C.dayNames[dayOfWeek];};$D.getMonthName=function(month,abbreviated){return(abbreviated&&typeof abbreviated=="boolean")?$C.abbreviatedMonthNames[month]:$C.monthNames[month];};$D.getMonthNumberFromName=function(name){var n=$C.monthNames,m=$C.abbreviatedMonthNames,s=name.toLowerCase();for(var i=0;i<n.length;i++){if(n[i].toLowerCase()==s||m[i].toLowerCase()==s){return i;}}
return-1;};$D.getDayNumberFromName=function(name){var n=$C.dayNames,m=$C.abbreviatedDayNames,o=$C.shortestDayNames,s=name.toLowerCase();for(var i=0;i<n.length;i++){if(n[i].toLowerCase()==s||m[i].toLowerCase()==s){return i;}}
return-1;};$D.isLeapYear=function(year){return(((year%4===0)&&(year%100!==0))||(year%400===0));};$D.getDaysInMonth=function(year,month){return[31,($D.isLeapYear(year)?29:28),31,30,31,30,31,31,30,31,30,31][month];};$D.getTimezoneOffset=function(s){return $C.timezones[s.toUpperCase()];};$D.getTimezoneAbbreviation=function(offset){var n=$C.timezones,p;for(var i=0;i<n.length;i++){if(n[i]===offset){return n[i];}}
return null;};$P.clone=function(){return new Date(this.getTime());};$P.compareTo=function(date){if(isNaN(this)){throw new Error(this);}
if(date instanceof Date&&!isNaN(date)){return(this>date)?1:(this<date)?-1:0;}else{throw new TypeError(date);}};$P.equals=function(date){return(this.compareTo(date)===0);};$P.between=function(start,end){var t=this.getTime();return t>=start.getTime()&&t<=end.getTime();};$P.addMilliseconds=function(value){this.setMilliseconds(this.getMilliseconds()+value);return this;};$P.addSeconds=function(value){return this.addMilliseconds(value*1000);};$P.addMinutes=function(value){return this.addMilliseconds(value*60000);};$P.addHours=function(value){return this.addMilliseconds(value*3600000);};$P.addDays=function(value){return this.addMilliseconds(value*86400000);};$P.addWeeks=function(value){return this.addDays(value*7);};$P.addMonths=function(value){var n=this.getDate();this.setDate(1);this.setMonth(this.getMonth()+value);this.setDate(Math.min(n,this.getDaysInMonth()));return this;};$P.addYears=function(value){return this.addMonths(value*12);};$P.add=function(config){if(typeof config=="number"){this._orient=config;return this;}
var x=config;if(x.millisecond||x.milliseconds){this.addMilliseconds(x.millisecond||x.milliseconds);}
if(x.second||x.seconds){this.addSeconds(x.second||x.seconds);}
if(x.minute||x.minutes){this.addMinutes(x.minute||x.minutes);}
if(x.hour||x.hours){this.addHours(x.hour||x.hours);}
if(x.week||x.weeks){this.addWeeks(x.week||x.weeks);}
if(x.month||x.months){this.addMonths(x.month||x.months);}
if(x.year||x.years){this.addYears(x.year||x.years);}
if(x.day||x.days){this.addDays(x.day||x.days);}
return this;};$D._validate=function(value,min,max,name){if(typeof value!="number"){throw new TypeError(value+" is not a Number.");}else if(value<min||value>max){throw new RangeError(value+" is not a valid value for "+name+".");}
return true;};$D.validateMillisecond=function(n){return $D._validate(n,0,999,"milliseconds");};$D.validateSecond=function(n){return $D._validate(n,0,59,"seconds");};$D.validateMinute=function(n){return $D._validate(n,0,59,"minutes");};$D.validateHour=function(n){return $D._validate(n,0,23,"hours");};$D.validateDay=function(n,year,month){return $D._validate(n,1,$D.getDaysInMonth(year,month),"days");};$D.validateMonth=function(n){return $D._validate(n,0,11,"months");};$D.validateYear=function(n){return $D._validate(n,1,9999,"years");};$P.set=function(config){var x=config;if(!x.millisecond&&x.millisecond!==0){x.millisecond=-1;}
if(!x.second&&x.second!==0){x.second=-1;}
if(!x.minute&&x.minute!==0){x.minute=-1;}
if(!x.hour&&x.hour!==0){x.hour=-1;}
if(!x.day&&x.day!==0){x.day=-1;}
if(!x.month&&x.month!==0){x.month=-1;}
if(!x.year&&x.year!==0){x.year=-1;}
if(x.millisecond!=-1&&$D.validateMillisecond(x.millisecond)){this.addMilliseconds(x.millisecond-this.getMilliseconds());}
if(x.second!=-1&&$D.validateSecond(x.second)){this.addSeconds(x.second-this.getSeconds());}
if(x.minute!=-1&&$D.validateMinute(x.minute)){this.addMinutes(x.minute-this.getMinutes());}
if(x.hour!=-1&&$D.validateHour(x.hour)){this.addHours(x.hour-this.getHours());}
if(x.month!==-1&&$D.validateMonth(x.month)){this.addMonths(x.month-this.getMonth());}
if(x.year!=-1&&$D.validateYear(x.year)){this.addYears(x.year-this.getFullYear());}
if(x.day!=-1&&$D.validateDay(x.day,this.getFullYear(),this.getMonth())){this.addDays(x.day-this.getDate());}
if(x.timezone){this.setTimezone(x.timezone);}
if(x.timezoneOffset){this.setTimezoneOffset(x.timezoneOffset);}
return this;};$P.isLeapYear=function(){var y=this.getFullYear();return(((y%4===0)&&(y%100!==0))||(y%400===0));};$P.isWeekday=function(){return!(this.is().sat()||this.is().sun());};$P.getDaysInMonth=function(){return $D.getDaysInMonth(this.getFullYear(),this.getMonth());};$P.moveToFirstDayOfMonth=function(){return this.set({day:1});};$P.moveToLastDayOfMonth=function(){return this.set({day:this.getDaysInMonth()});};$P.moveToNthOccurrence=function(dayOfWeek,occurrence){var shift=0;if(occurrence){if(occurrence>0){shift=occurrence-1;}else if(occurrence==-1){return this.moveToLastDayOfMonth().moveToDayOfWeek(dayOfWeek,-1);}}
return this.moveToFirstDayOfMonth().addDays(-1).moveToDayOfWeek(dayOfWeek,+1).addWeeks(shift);};$P.moveToDayOfWeek=function(dayOfWeek,orient){var diff=(dayOfWeek-this.getDay()+7*(orient||+1))%7;return this.addDays((diff===0)?diff+=7*(orient||+1):diff);};$P.moveToMonth=function(month,orient){var diff=(month-this.getMonth()+12*(orient||+1))%12;return this.addMonths((diff===0)?diff+=12*(orient||+1):diff);};$P.getDayOfYear=function(){return Math.floor((this-new Date(this.getFullYear(),0,1))/86400000);};$P.getWeekOfYear=function(firstDayOfWeek){var y=this.getFullYear(),m=this.getMonth(),d=this.getDate();var dow=firstDayOfWeek||$C.firstDayOfWeek;var offset=7+1-new Date(y,0,1).getDay();if(offset==8){offset=1;}
var daynum=(($D.UTC(y,m,d,0,0,0)-$D.UTC(y,0,1,0,0,0))/86400000)+1;var w=Math.floor((daynum-offset+7)/7);if(w===dow){y--;var prevOffset=7+1-new Date(y,0,1).getDay();if(prevOffset==2||prevOffset==8){w=53;}else{w=52;}}
return w;};$P.isDST=function(){return this.toString().match(/(E|C|M|P)(S|D)T/)[2]=="D";};$P.getTimezone=function(){return $D.getTimezoneAbbreviation(this.getUTCOffset);};$P.setTimezoneOffset=function(s){var here=this.getTimezoneOffset(),there=Number(s)*-6/10;return this.addMinutes(there-here);};$P.setTimezone=function(s){return this.setTimezoneOffset($D.getTimezoneOffset(s));};$P.getUTCOffset=function(){var n=this.getTimezoneOffset()*-10/6,r;if(n<0){r=(n-10000).toString();return r[0]+r.substr(2);}else{r=(n+10000).toString();return"+"+r.substr(1);}};$P.getElapsed=function(date){return(date||new Date())-this;};$P.getDayName=function(abbreviated){return $D.getDayName(this.getDay(),(abbreviated||false));};$P.getMonthName=function(abbreviated){return $D.getMonthName(this.getMonth(),(abbreviated||false));};$P._toString=$P.toString;$P.toString=function(format){var me=this;var p=function p(s){return(s.toString().length==1)?"0"+s:s;};return format?format.replace(/dd?d?d?|MM?M?M?|yy?y?y?|hh?|HH?|mm?|ss?|tt?|zz?z?/g,function(format){switch(format){case"hh":return p(me.getHours()<13?me.getHours():(me.getHours()-12));case"h":return me.getHours()<13?me.getHours():(me.getHours()-12);case"HH":return p(me.getHours());case"H":return me.getHours();case"mm":return p(me.getMinutes());case"m":return me.getMinutes();case"ss":return p(me.getSeconds());case"s":return me.getSeconds();case"yyyy":return me.getFullYear();case"yy":return me.getFullYear().toString().substring(2,4);case"dddd":return me.getDayName();case"ddd":return me.getDayName(true);case"dd":return p(me.getDate());case"d":return me.getDate().toString();case"MMMM":return me.getMonthName();case"MMM":return me.getMonthName(true);case"MM":return p((me.getMonth()+1));case"M":return me.getMonth()+1;case"t":return me.getHours()<12?$C.amDesignator.substring(0,1):$C.pmDesignator.substring(0,1);case"tt":return me.getHours()<12?$C.amDesignator:$C.pmDesignator;case"zzz":case"zz":case"z":return"";}}):this._toString();};}());
